import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../styles/style.module.scss";
import Header from "@/components/Header";
import Timeline from "@/components/Timeline";
import Post from "@/components/Post";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Gs graduation work</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={styles.container}>
        <Timeline />
        <Post />
      </main>
    </>
  );
}